# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ebccdd4ec1808940ad8ce6df469d2bad88fa1c1220a0d4f35f7739ee370d5c397afb08301d5bb5264ccc7ccc0b8a6bc7168247909c1a4798bf3ec633b41bfe

test:
  secret_key_base: bf5c85de8f8b20ff8d0bc5957e32b67478e80aa09b3a4b92e6cd3fb3dd47af7aca6e6cba12afd0ceec61a3443352ff95221f448db4beac5fe8c038c651f0cc37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
