# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc704615ab8813db835d50dd40a442bd8e83f91d3cd3b51c75decbcdc707a8f89512b1a6335c1741d3b2676b643a43714db189db2e41ac8450768c14ebfd47da

test:
  secret_key_base: 58adf98871d4c49888cb70f8f3d0d01ac5baba80902e4b3cb6cb6e26ed859e9132e132bb582a746925d2e019bb1be2a30f250a227533baf063d4753cb595696b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
